Flavor.create_with(dairy: true).find_or_create_by(name: "chocolate")
Flavor.create_with(dairy: true).find_or_create_by(name: "vanilla")
Flavor.create_with(dairy: true).find_or_create_by(name: "strawberry")
Flavor.create_with(dairy: true).find_or_create_by(name: "mint")
Flavor.create_with(dairy: true).find_or_create_by(name: "neopolitan")
Flavor.create_with(dairy: true).find_or_create_by(name: "toffee")
Flavor.create_with(dairy: true).find_or_create_by(name: "caramel")
Flavor.create_with(dairy: true).find_or_create_by(name: "peanut butter")
Flavor.create_with(dairy: true).find_or_create_by(name: "coffee")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free chocolate")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free vanilla")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free strawberry")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free mint")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free neopolitan")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free toffee")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free caramel")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free peanut butter")
Flavor.create_with(dairy: false).find_or_create_by(name: "dairy-free coffee")
Mix.create_with(choclate: false, nuts: false, fruits: false, other: false).find_or_create_by(name: "none")
Mix.create_with(choclate: true, nuts: true, fruits: false, other: false).find_or_create_by(name: "peanut butter cups")
Mix.create_with(choclate: true, nuts: true, fruits: false, other: false).find_or_create_by(name: "reese pieces")
Mix.create_with(choclate: true, nuts: false, fruits: false, other: false).find_or_create_by(name: "brownies")
Mix.create_with(choclate: true, nuts: false, fruits: false, other: false).find_or_create_by(name: "fudge")
Mix.create_with(choclate: true, nuts: false, fruits: false, other: false).find_or_create_by(name: "choclate chips")
Mix.create_with(choclate: true, nuts: false, fruits: false, other: false).find_or_create_by(name: "M&Ms")
Mix.create_with(choclate: true, nuts: true, fruits: false, other: false).find_or_create_by(name: "butterfingers")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "pecans")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "salted pecans")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "almonds")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "honey peanuts")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "peanuts")
Mix.create_with(choclate: false, nuts: true, fruits: false, other: false).find_or_create_by(name: "walnut")
Mix.create_with(choclate: false, nuts: false, fruits: true, other: false).find_or_create_by(name: "strawberries")
Mix.create_with(choclate: false, nuts: false, fruits: true, other: false).find_or_create_by(name: "bananas")
Mix.create_with(choclate: false, nuts: false, fruits: true, other: false).find_or_create_by(name: "blueberry")
Mix.create_with(choclate: false, nuts: false, fruits: true, other: false).find_or_create_by(name: "raspberries")
Mix.create_with(choclate: false, nuts: false, fruits: true, other: false).find_or_create_by(name: "mango")
Mix.create_with(choclate: false, nuts: false, fruits: false, other: true).find_or_create_by(name: "marshmallows")
Mix.create_with(choclate: false, nuts: false, fruits: false, other: true).find_or_create_by(name: "oreos")
Mix.create_with(choclate: false, nuts: false, fruits: false, other: true).find_or_create_by(name: "cookie dough")
Mix.create_with(choclate: false, nuts: false, fruits: false, other: true).find_or_create_by(name: "nerds")
Toppin.find_or_create_by(name: "none")
Toppin.find_or_create_by(name: "whipped cream")
Toppin.find_or_create_by(name: "caramel")
Toppin.find_or_create_by(name: "hot fudge")
Toppin.find_or_create_by(name: "choclate sauce")
Toppin.find_or_create_by(name: "sprinkles")
Special.create_with(description: "Chocolate icecream with nuts and marshmallows").find_or_create_by(name: "Rocky Road")
Special.create_with(description: "Vanilla icecream with fudge, peanut butter cups, and choclate sauce").find_or_create_by(name: "Moose Tracks")